spring:
  datasource:
    url: jdbc:h2:mem:memDB
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        opaque:
          introspection-uri: http://localhost:8000/o/introspect/
          introspection-client-id: DzVhTA1vzxpo3DFIeBse2cHjX1EXj095Fs0Gm7WX
          introspection-client-secret: p9eeH4kN9J3Lya2ZtOk89CQpj57qFXzjeV4OKUujZeiFjfbMdamb5kylQQEolO3ha1RttlcXeaYNbcb8G3dm3jcHoUZc8Hjcw3HOt5rBfTm3HLCDta9YxaZ6Cu8LPjVX
